services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: backend
    ports:
      - "8080:8080"
    depends_on:
      - mosquitto 

  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
